# the usage of numpy.add

In [3]:
import numpy as np

In [9]:
"""
exmaple1:
"""
in_num1 = 10
in_num2 = 15
print("first input number:",in_num1)
print("second input number:",in_num2)

out_num = np.add(in_num1,in_num2)
print("out_num:",out_num)

first input number: 10
second input number: 15
out_num: 25


In [11]:
"""
example2:
"""
in_arr1 = np.array([[2,-7,5],[-6,2,0]])
in_arr2 = np.array([[5,8,-5],[3,6,9]])

print("in_arr1.shape:{}".format(in_arr1.shape))
print(in_arr1)
print("********")
print("in_arr2.shape:{}".format(in_arr2.shape))
print(in_arr2)
print("********")

out_arr = np.add(in_arr1,in_arr2)
print("out_arr.shape:{}".format(out_arr.shape))
print(out_arr)

in_arr1.shape:(2, 3)
[[ 2 -7  5]
 [-6  2  0]]
********
in_arr2.shape:(2, 3)
[[ 5  8 -5]
 [ 3  6  9]]
********
out_arr.shape:(2, 3)
[[ 7  1  0]
 [-3  8  9]]


In [16]:
"""
official example
"""

np.add(1.0,4.0)

5.0

In [35]:
x1 = np.arange(9.0).reshape((3,3))
print("x1.shape:{}".format(x1.shape))
print(x1)
print("********")
x2 = np.arange(3.0)
print("x2.shape:{}".format(x2.shape))
print(x2)
add_ret = np.add(x1,x2)
print("add_ret.shape:{}".format(add_ret.shape))
print(add_ret)

x1.shape:(3, 3)
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
********
x2.shape:(3,)
[0. 1. 2.]
add_ret.shape:(3, 3)
[[ 0.  2.  4.]
 [ 3.  5.  7.]
 [ 6.  8. 10.]]


# the usage of numpy.split

In [1]:
import numpy as np

In [12]:
a = np.arange(9)
print("a.shape:{}".format(a.shape))
print(a)

print("*********")

print("split the array into 3 sub_array:")
b = np.split(a,3)
print(b)

print("*********")

c = np.split(a,[1,3,7])
print(c)

a.shape:(9,)
[0 1 2 3 4 5 6 7 8]
*********
split the array into 3 sub_array:
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
*********
[array([0]), array([1, 2]), array([3, 4, 5, 6]), array([7, 8])]


In [13]:
pwd

'/home/zhubin/LangYangTech/notebook'